### ISSUE TITLE
Feat: Project setup and overview 

### ISSUE THREAD

**Issue by yashksaini-coder** [kvcops/KV-Nexus#1]
I would like to work on this as GSSoC contributor

@kvcops assign me this issue

**Comment by techy4shri** [comment]
Explain what setup you will add. Unless the info is provided this issue will not be accepted.

**Comment by yashksaini-coder** [comment]
simply creating a new readme doc, that will guide a beginner what api values they need to have and clear steps how to obtain them, as the project uses a lot, few images & small vids can be helpful. Some are easy some and for some I need time.

**Comment by techy4shri** [comment]
That is not needed, this is a github repository, not an education point. Closing this because it is not needed.
