### ISSUE TITLE
adding readme file

### ISSUE THREAD

**Issue by agarwalbhargavi** [kvcops/KV-Nexus#10]
i would like to add a read me file to this project.

**Comment by agarwalbhargavi** [comment]
@kvcops please assign me this issue

**Comment by kvcops** [comment]
Ok ..

**Comment by agarwalbhargavi** [comment]
@kvcops please atleast add level2 label becuse the documentation part is alot and i have to create a new file itself.

**Comment by agarwalbhargavi** [comment]
@kvcops please also add gssoc and hacktoberfest labels

**Comment by agarwalbhargavi** [comment]
@kvcops  hacktoberfest?

**Comment by agarwalbhargavi** [comment]
@kvcops is this project accepted for hacktoberfest or not ..beacuse i have to add banner in read me file. kindly rely asap

**Comment by kvcops** [comment]
I mean there is no label as hacktoberfest...

**Comment by agarwalbhargavi** [comment]
@kvcops yes please i am done with readme file. if you can check it fast i can make a pr as soon as possible

**Comment by agarwalbhargavi** [comment]
its fine i'll submit my pr now ..you can add labels there also gssoc haktoberfest and level2.

**Comment by kvcops** [comment]
Is there any chance to shorten the readme file...it looks so long enough...also if possible try to use simple terminology

**Comment by agarwalbhargavi** [comment]
@kvcops which section u want me to remove?

**Comment by kvcops** [comment]
There's no need to remove...just decrease the information and make it more readable...make it short and simple ...also improve the readme layout for a better view

**Comment by agarwalbhargavi** [comment]
@kvcops  layout as in?

**Comment by agarwalbhargavi** [comment]
<img width="684" alt="Screenshot 2024-10-25 203217" src="https://github.com/user-attachments/assets/4dece06e-1edc-45fe-9e75-4d98f71b5bba">
i hope there is no issue with this part @kvcops

**Comment by kvcops** [comment]
I mean the formatting...the alignment etc

**Comment by agarwalbhargavi** [comment]
oh allright @kvcops

**Comment by agarwalbhargavi** [comment]
@kvcops i have made  new PR kindly review and revert

**Comment by kvcops** [comment]
Yep.. this looks far better . Really good. Thanks for the help 🙂

**Comment by agarwalbhargavi** [comment]
@kvcops  kindly merge it with main also please add the label. :)

**Comment by agarwalbhargavi** [comment]
@kvcops can you please add the labels in my PR as without them the PR will not be considered for gssoc and hacktovberfest
