### ISSUE TITLE
Adding the footer elements

### ISSUE THREAD

**Issue by likitha-kapu** [kvcops/KV-Nexus#101]
The footer looks simple ...Enhanching the footer and adding new links for easy navigation of the website....This enables user to easily access through the webpage.
I wish to add about us ,quicklinks,social media components in the footer
![Screenshot 2024-11-09 084745](https://github.com/user-attachments/assets/e4931c8b-76ab-49e3-87b9-465cdf9ec046)
At present it has only social icons.I wish to enhance it .

**Comment by likitha-kapu** [comment]
@kvcops please assign this task with a level2 label

**Comment by kvcops** [comment]
It's not an issue...also for normal change in the css for the footer we can't assign level 2...so closing this issue...hoping for more contributions from you in the future @likitha-kapu
