### ISSUE TITLE
About heading not visible while navigating through navbar

### ISSUE THREAD

**Issue by Lakshay1406** [kvcops/KV-Nexus#102]
![image](https://github.com/user-attachments/assets/7507ae31-aa8a-49f6-9cd3-6fbdd7a1dd6e)
when clicking the "About" in the navbar the heading does not come to display.
just going to align the scroll amount to make it correct.
so it looks like the image below.
![image](https://github.com/user-attachments/assets/7f507f3d-d134-492f-b2f8-a2a331b8b284)

**Comment by techy4shri** [comment]
@Lakshay1406 how will you improve it?

**Comment by Lakshay1406** [comment]
by adjusting the offset value. so when clicked the heading is also visible when clicked through nav bar.

**Comment by Lakshay1406** [comment]
Done! PR raised [#118 ](https://github.com/kvcops/KV-Nexus/pull/118) kindly approve.
