### ISSUE TITLE
Enhance the text "The Future of AI is Here" dynamic typing style 

### ISSUE THREAD

**Issue by laxmikandivalasa** [kvcops/KV-Nexus#112]
I want to enhance the text "The Future of AI is Here" dynamic typing style. please assign me......

**Comment by techy4shri** [comment]
@laxmikandivalasa you need to make the PR by tonight.

**Comment by laxmikandivalasa** [comment]
sure!!

**Comment by techy4shri** [comment]
@laxmikandivalasa but first, how will you enhance it?

**Comment by techy4shri** [comment]
not needed at the moment. Closing this.
