### ISSUE TITLE
Overlap fix of buttons and cards to Cutting-Edge AI Tools section

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [kvcops/KV-Nexus#116]
in your website at Cutting-Edge AI Tools this section in all cards the the button and information about cards are like overlap i want to fix this to make this section and all of this cards visibly good.

![WhatsApp Image 2024-11-10 at 10 49 03_ba8132d9](https://github.com/user-attachments/assets/1ebf64a2-c537-4a23-833a-d771adfb6e9d)

**Comment by kvcops** [comment]
Yep...fix this issue
