### ISSUE TITLE
Navbar overlap fix for small device

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [kvcops/KV-Nexus#117]
for small device at navbar the navbar icon and Hyderabad: haze, 27.2°C this text are overlap with each other i want to fix this.

![WhatsApp Image 2024-11-10 at 10 52 30_d06af636](https://github.com/user-attachments/assets/efb46bc9-2a0d-4901-b9c1-7c0bb0bf8826)

**Comment by kvcops** [comment]
This is not an issue...and there are no screens that really use these dimensions...
