### ISSUE TITLE
Webpage Ui/Ux fixation

### ISSUE THREAD

**Issue by swatified** [kvcops/KV-Nexus#15]
Hey I figured out that current ui is not as friendly and moving gradients all across website are making it hard to read. I wanna improve overall ui of the website by still keeping it dark themed but minimalistic and useful. Can you please assign this to me under gssoc-ext and hacktoberfest-accepted? we can set levels later based on work, don't worry.

... (P.S. Do you want me to keep that web background at home or can I remove that?)

**Comment by swatified** [comment]
@kvcops @Wahid7852

**Comment by kvcops** [comment]
Give it a try I would like to see it ...if I found it interesting I'll merge it

**Comment by ShashwatAgrawal20** [comment]
hey @swatified, are you still working on this? How's the progress so far?

**Comment by swatified** [comment]
@ShashwatAgrawal20 Yes I have done the basic color fixation. Moving onto to structure change now. Wonderimg if I should remove that 3d net bg from hero section. Should I?

**Comment by Wahid7852** [comment]
@swatified lets chat on discord for a better understanding of what to do with the PA. I will be inviting you to the chat soon

**Comment by techy4shri** [comment]
@swatified update?

**Comment by swatified** [comment]
@techy4shri You can close the issue. I am unable to get the time to get it done. Sorry

**Comment by Wahid7852** [comment]
Closed due to contributor being busy.
