### ISSUE TITLE
Adding sign Up page 

### ISSUE THREAD

**Issue by RahulPrasadYadav** [kvcops/KV-Nexus#19]
Streamlined User Experience: A dedicated sign-up page provides users with a clear, focused experience, guiding them through the registration process without distractions. It’s also an opportunity to explain the platform's benefits and show why signing up is worthwhile.

Improved Conversion Rates: With clear calls to action (CTAs) and a straightforward design, a sign-up page can encourage more users to complete the registration. Features like social logins (e.g., Google, Facebook, X) and auto-fill fields can further reduce friction.

Data Collection and User Insights: The sign-up process allows businesses to collect basic user information such as name, email, and preferences. This data is valuable for creating a personalized user experience, segmenting audiences, and improving marketing efforts.

**Comment by RahulPrasadYadav** [comment]
@kvcops assign the issue

**Comment by kvcops** [comment]
which database would you like to use for storing the credentials of the user ?

**Comment by RahulPrasadYadav** [comment]
Sql

**Comment by kvcops** [comment]
I mean can u use the google firebase and Firestore to store up the credentials

**Comment by RahulPrasadYadav** [comment]
I will try

**Comment by kvcops** [comment]
Ok

**Comment by Wahid7852** [comment]
tell me a proper approach @RahulPrasadYadav and i will assign you.

**Comment by ShashwatAgrawal20** [comment]
hey @RahulPrasadYadav are you still going to work on this? If you don't reply by **Today 12PM**, this issue will be open to grab by anyone.

**Comment by yashksaini-coder** [comment]
> hey @RahulPrasadYadav are you still going to work on this? If you don't reply by **Today 12PM**, this issue will be open to grab by anyone.

@ShashwatAgrawal20 @kvcops can I work on it ?

**Comment by ShashwatAgrawal20** [comment]
You're the wizard for this one! Let's make magic happen! 

![assigned](https://github.com/user-attachments/assets/64ae508d-76cc-46cf-bd93-05a88f18c64d)

**Comment by kvcops** [comment]
Ok...work it on...

**Comment by yashksaini-coder** [comment]
> Ok...work it on...

sure once my Mom stop assigning tasks, then I can work on assigned issues :sweat_smile:

**Comment by kvcops** [comment]
Be waiting for it

**Comment by techy4shri** [comment]
@yashksaini-coder are you still working on this?

**Comment by kvcops** [comment]
no need for it...cause i worked and created it ...the task is completed

**Comment by yashksaini-coder** [comment]
@techy4shri yes I am, creating flask db to store creds, but the build is failing so trying to figure it out.

**Comment by yashksaini-coder** [comment]
> no need for it...cause i worked and created it ...the task is completed

if so then you can close this issue

**Comment by kvcops** [comment]
Ok @yashksaini-coder
