### ISSUE TITLE
Fix the back to Top button 

### ISSUE THREAD

**Issue by yashksaini-coder** [kvcops/KV-Nexus#2]
I am planning to fix the Back to top button in the bottom left corner. 

@kvcops assign this issue to me, as gssoc contributor.

**Comment by yashksaini-coder** [comment]
@kvcops why is this issue assigned to @Wahid7852 ??

**Comment by kvcops** [comment]
> @kvcops why is this issue assigned to @Wahid7852 ??

sorry...my mistake...i pressed it unfortunately

**Comment by yashksaini-coder** [comment]
> > @kvcops why is this issue assigned to @Wahid7852 ??
> 
> sorry...my mistake...i pressed it unfortunately

okay no problem just making sure that I am working on it

**Comment by ShashwatAgrawal20** [comment]
hey @yashksaini-coder are you still working on it? 

and I don't think this should be a level2 issue? @Wahid7852 @jindalpriyanshu101 @techy4shri

**Comment by jindalpriyanshu101** [comment]
Its a minor fix, Reduced to level 1

**Comment by yashksaini-coder** [comment]
> hey @yashksaini-coder are you still working on it?
> 
> and I don't think this should be a level2 issue? @Wahid7852 @jindalpriyanshu101 @techy4shri

I am just need some time

**Comment by techy4shri** [comment]
@kvcops this won't be worked on, correct?

**Comment by kvcops** [comment]
Yep ..this issue is fixed
