### ISSUE TITLE
Adding a Custom Preloader 

### ISSUE THREAD

**Issue by Peart-Guy** [kvcops/KV-Nexus#20]
I want to add a custom preloader to the webapp which will match the aesthetic and theme of the website

@kvcops  Kindly assign me the work

This is a basic sample to showcase what I can offer. The final product may vary depending on your specific needs and preferences. I look forward to the opportunity to contribute to your project .

https://github.com/user-attachments/assets/61bb5ec0-9aac-4131-aa48-84dd094a5abd

**Comment by kvcops** [comment]
actually the thing is we deployed this on the vercel which results in about 5 seconds to load up for the index.html ...adding this would delay more time. Check for any alternative methods and ideas that you have...
