### ISSUE TITLE
write a better description on 'about kv nexus' for better understanding of the website for the viewers

### ISSUE THREAD

**Issue by PreetiTamana** [kvcops/KV-Nexus#22]
write a better description on 'about kv nexus' for better understanding of the website for the viewers and a making it more engaging

**Comment by kvcops** [comment]
Suggest the description matter...but make sure it has to be simple , short and also should contain commonly used terminology rather than using some complex words

**Comment by PreetiTamana** [comment]
> Suggest the description matter...but make sure it has to be simple , short and also should contain commonly used terminology rather than using some complex words

**Comment by PreetiTamana** [comment]
> Suggest the description matter...but make sure it has to be simple , short and also should contain commonly used terminology rather than using some complex words

sure

**Comment by ShashwatAgrawal20** [comment]
@PreetiTamana what did you closed the issue?

**Comment by PreetiTamana** [comment]
> @PreetiTamana what did you closed the issue?

Sry by mistake
