### ISSUE TITLE
Fix the file upload bug

### ISSUE THREAD

**Issue by yashksaini-coder** [kvcops/KV-Nexus#3]
Using vercel, the file upload is limited, I would like to work on alternative deployment setup

Can you assign this issue to me @kvcops

**Comment by Wahid7852** [comment]
@yashksaini-coder ONE AT A TIME
i will assign you after you complete your already assigned issues

**Comment by yashksaini-coder** [comment]
> Reference

okh, also can you add labels on the other ones

**Comment by kvcops** [comment]
How about only deploying the document summarizer into the render and then add that href link to the index.html for the doc summarizer .

**Comment by kvcops** [comment]
Ok

**Comment by techy4shri** [comment]
Where is the bug in this? @yashksaini-coder Do not give any title to your issue simply fo the sake of it or it will be rejected.
