### ISSUE TITLE
Add language Translator so that more user can read and use this website 

### ISSUE THREAD

**Issue by HimangshuSharma01** [kvcops/KV-Nexus#30]
![image](https://github.com/user-attachments/assets/8dbd8943-8b8b-47ef-9ffd-8cd04eb962c8)
I can work in this

**Comment by kvcops** [comment]
Which translate api would you like to use for this ?

**Comment by HimangshuSharma01** [comment]
> Which translate api would you like to use for this ?

google

**Comment by kvcops** [comment]
So you are adding an option to convert the whole webpage into a preferred language...or only to the generated text by the gemini model ?

**Comment by HimangshuSharma01** [comment]
whole webpage

**Comment by kvcops** [comment]
Can you only try it for the generated text output by the gemini model...

**Comment by HimangshuSharma01** [comment]
like when we generate the text it will be in the asked language and other elements will be in english?

**Comment by HimangshuSharma01** [comment]
The think i was trying to add will change change the entire website texts to the prefered language

**Comment by kvcops** [comment]
I mean after generation of the output there should be a button . And when we click on that button the generated text should translate (only the output text not the complete webpage page)

**Comment by HimangshuSharma01** [comment]
okay i understood

**Comment by HimangshuSharma01** [comment]
yeah i can work in this

**Comment by kvcops** [comment]
Ok...

**Comment by kvcops** [comment]
hey...actually there are bugs in this...the translated text gets out of the container and overflows . also  this feature is not working for the psychology prediction and health analysis

**Comment by kvcops** [comment]
can you look into this and fix this bugs ?

**Comment by HimangshuSharma01** [comment]
> can you look into this and fix this bugs ?

I'm trying to fix

**Comment by HimangshuSharma01** [comment]
> can you look into this and fix this bugs ?

Hey I can do one thing none of the texts will overflow just have a look at the conversational I want to implement the similar thing

**Comment by kvcops** [comment]
> > can you look into this and fix this bugs ?
> 
> Hey I can do one thing none of the texts will overflow just have a look at the conversational I want to implement the similar thing

yep...similar to the Conversational AI just do the modifications to the recipe , psychology and health ...also add this feature to the story generator

**Comment by HimangshuSharma01** [comment]
If you allow me to do so I can do it within some time if not it will require some time.

**Comment by HimangshuSharma01** [comment]
> > > can you look into this and fix this bugs ?
> > 
> > Hey I can do one thing none of the texts will overflow just have a look at the conversational I want to implement the similar thing
> 
> yep...similar to the Conversational AI just do the modifications to the recipe , psychology and health ...also add this feature to the story generator

Okaaay

**Comment by kvcops** [comment]
Yep...been waiting for the changes

**Comment by kvcops** [comment]
thanks for your contribution :)
