### ISSUE TITLE
UI; add a favicon to the site 

### ISSUE THREAD

**Issue by AE-Hertz** [kvcops/KV-Nexus#31]
add a favicon to the site, that will help to website look good.

assign me this under hacktoberfest and gssoc-ext

**Comment by kvcops** [comment]
Ok...

**Comment by AE-Hertz** [comment]
@kvcops requested a PR #34

**Comment by kvcops** [comment]
Yep...thanks for contributing

**Comment by techy4shri** [comment]
this issue will remain open till the pr is merged
