### ISSUE TITLE
feat: add a contributors page

### ISSUE THREAD

**Issue by AE-Hertz** [kvcops/KV-Nexus#32]
add a page to feature all the developers who worked on this awesome project.

assign me this under hacktoberfest and gssoc-ext , and i expect level 3 for this.

**Comment by kvcops** [comment]
sure ...will consider it !!

**Comment by jindalpriyanshu101** [comment]
Reduced to level1, as Level 3 isn't justified for such update.

**Comment by AE-Hertz** [comment]
@kvcops dont do this, i have already wrote more than 500 lines of code, and page is almost ready.

**Comment by AE-Hertz** [comment]
@jindalpriyanshu101 sir please refer other projects too, its considered as level 3 .

**Comment by techy4shri** [comment]
@AE-Hertz If you wrote 500 lines of code for a simple issue, then that is another issue. Adding a contributors page is a simple begineer level issue and no matter the number of lines in a code, it is the complexity of it which determines the level.

**Comment by AE-Hertz** [comment]
@techy4shri if thats the case, decide it during PR, . as far as i know handling apis is not a beginner level stuff.

**Comment by ShashwatAgrawal20** [comment]
> @jindalpriyanshu101 sir please refer other projects too, its considered as level 3 . i am not making a readme file here.

can you link those **OTHER PROJECTS**, their points will be reduced as well.

**Comment by kvcops** [comment]
Here it all depends upon the ui that you make...I was hoping you would make the ui as good as the index.html with animations and transitions

**Comment by techy4shri** [comment]
@AE-Hertz, labels are assigned strictly in accordance with the intrinsic complexity of the issue, not predicated upon an arbitrary metric such as personal knowledge. Furthermore, I have yet to encounter any verifiable evidence pertaining to these OTHER PROJECTS you referenced. I strongly advise you to either concentrate on the task at hand, or this issue will be summarily locked and permanently disregarded.
