### ISSUE TITLE
New feature: New prompt to generate data plots

### ISSUE THREAD

**Issue by yashksaini-coder** [kvcops/KV-Nexus#4]
I want to work on the new feature to generate plots from the user given data.

@kvcops can you assign this issue to me

**Comment by techy4shri** [comment]
Explain your approach otherwise this issue will be rejected.

**Comment by yashksaini-coder** [comment]
simply using the csv files as input, then analyzing what type of data is there, and then showing all the plots that can be created. if one plot is not applicable on the dataset then we will let the user know that it does not support tha data plot as the original dataset provided lacks the data type in columns
