### ISSUE TITLE
Adding MIT license and Security.md file.

### ISSUE THREAD

**Issue by Nelcy17** [kvcops/KV-Nexus#44]
MIT License is a widely used, permissive open-source license.

A Security.md file is a document typically added to the root of a project’s repository to outline the security policies.

**Comment by kvcops** [comment]
Yep ....work it on

**Comment by kvcops** [comment]
Can you make the text formatting better with better headings and proper spaces and all.

**Comment by techy4shri** [comment]
@kvcops the MIT License is chosen when you make the repositry, we don't need this, nor the security file. We are not a hotshot company looking to make security policies.
@Nelcy17 I would suggest you refrain from making spam issues.
