### ISSUE TITLE
Enchancing script.js

### ISSUE THREAD

**Issue by smog-root** [kvcops/KV-Nexus#46]
**1. Duplicate Code in `DOMContentLoaded` Event:**

- The code to append messages, handle the message sending, and toggle the theme appears twice. It would be best to consolidate these to avoid redundancy and improve maintainability.

**2. Message Scrolling Enhancement:**

You have two scrolling functions:
-  `scrollToBottom` and `smoothScrollToBottom`, but it seems `smoothScrollToBottom` is the intended method. You can replace calls to `scrollToBottom` with `smoothScrollToBottom` to ensure a consistent, smooth scrolling experience.

**3. Unnecessary Re-declarations:**

- `messagesContainer`, `userInput`, and `sendButton` are declared twice. Since they’re used globally within the script, you only need to define them once.

**4. Optimizing the `appendMessage` Function:**

- Your `appendMessage` function already handles scrolling, but it might be cleaner to pass control to `smoothScrollToBottom` as an internal helper within that function.

**_Kindly add gssoc-ext with level and hacktoberfest-accepted labels_** @kvcops

**Comment by kvcops** [comment]
Ok...fix the issues

**Comment by smog-root** [comment]
Can you make it level2?? It's worth it. I'm fixing multiple issues in this!! @kvcops

**Comment by kvcops** [comment]
I mean these are very small minor issues...that can be fixed within minutes...

**Comment by kvcops** [comment]
Though it seems these are multiple but all of them are just issues that can be fixed easily ...so I am sorry that I can't add it to level 2

**Comment by smog-root** [comment]
@kvcops okay. I can do that. But you didn't add labels to my last PR too!! Please add the labels to my last PR and assign me!!

**Comment by kvcops** [comment]
Ok...will add it up
