### ISSUE TITLE
Feature : When user clicks on logo it should scroll up

### ISSUE THREAD

**Issue by ygowthamr** [kvcops/KV-Nexus#49]
### Issue Description: Scroll to Top on Logo Click

1. **Feature Implementation:** Clicking the logo should trigger smooth scrolling to the top of the page.
2. **User Experience:** Enhance navigation by allowing users to quickly access the top content.
3. **Cross-Browser Compatibility:** Ensure smooth scrolling works across all major browsers.
4. **Edge Case Handling:** Avoid unnecessary scroll events when the page is already at the top.
5. **Testing:** Verify the functionality on both desktop and mobile devices for consistency.

**Image for reference:**
- ![image](https://github.com/user-attachments/assets/b3b60dbb-5a14-4003-85b1-485b6f63d425)
@kvcops Pls assign me this issue and give me level2,gssoc-extd,hacktoberfest.

**Comment by ygowthamr** [comment]
@kvcops 
Can you pls assign me this issue and give me required labels

**Comment by kvcops** [comment]
ok

**Comment by kvcops** [comment]
Thanks for your contribution...i was hoping for more contributions from you in the future
