### ISSUE TITLE
Enhance chat box

### ISSUE THREAD

**Issue by EvanSingee** [kvcops/KV-Nexus#52]
Feature ISSUES:

- GTranslate Integration
- Accessibility Features
- Aria-labels
- Flexible Layout
- Overflow Control

UI ISSUES:

- Enhanced Theme Toggle
- Smooth Transition
- Icon Visibility
- Automatic Welcome Message
- Browser Language Detection

I'd like to contribute these.
Pls do add gssoc extd,hacktoberfest labels.
@kvcops

**Comment by kvcops** [comment]
try on the new features and let me know...as i want to see the changes in the ui that you make

**Comment by Wahid7852** [comment]
Waiting for your update @EvanSingee

**Comment by ShashwatAgrawal20** [comment]
@EvanSingee 

CC: @Wahid7852 @kvcops @techy4shri

**Comment by kvcops** [comment]
It seems like we have to Close the issue...it takes a lot more time than expected

**Comment by techy4shri** [comment]
Closing this then @kvcops
