### ISSUE TITLE
Adding About us and linking it to navbar

### ISSUE THREAD

**Issue by Bhum-ika** [kvcops/KV-Nexus#6]
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by kvcops** [comment]
ok...

**Comment by ShashwatAgrawal20** [comment]
![it-already-exists](https://github.com/user-attachments/assets/bf6af051-4993-49a5-8c46-d378e367249d)

**CLOSING**

**Comment by ShashwatAgrawal20** [comment]
duplicate #29
