### ISSUE TITLE
Header Overlap: Weather Info and Hamburger Icon on Small Screens

### ISSUE THREAD

**Issue by shivhere007** [kvcops/KV-Nexus#60]
Issue Description:
The header section on small screens (e.g., 425px width) has an overlap issue where the weather information text (Ranchi: mist, 26.1°C) overlaps with the hamburger menu icon. This reduces readability and affects the usability of the menu.

![Screenshot 2024-10-28 165637](https://github.com/user-attachments/assets/e56dd4ea-401b-453e-bd82-3348338e2e17)

Steps to Reproduce:
* Open the application on a small screen device or resize the browser to a width of 425px or less.
* Observe the header section with the weather info and hamburger icon.

Expected Behavior:
The weather information text and hamburger icon should be clearly visible without overlapping, allowing users to access the menu easily and read the weather information.

Actual Behavior:
The weather information and hamburger icon overlap, making both elements difficult to interact with or read.

This fix should improve the user experience by ensuring all header elements are properly aligned and readable across various screen sizes. Kindly assign it to me @kvcops

**Comment by techy4shri** [comment]
@shivhere007 can you tell me a device which has such screen dimensions?

**Comment by shivhere007** [comment]
@techy4shri Here are some devices : 
Ipad mini 
![Screenshot 2024-10-28 173001](https://github.com/user-attachments/assets/3f161923-1bf8-4908-942a-cce4315ec6d0)

Samsung galaxy s20 ultra
![Screenshot 2024-10-28 173018](https://github.com/user-attachments/assets/533bacbe-be74-4056-9a70-608b4a8aabbb)

Iphone 14 pro max 
![Screenshot 2024-10-28 173034](https://github.com/user-attachments/assets/ffc9cd78-22b3-4f36-8977-fc90a1add217)

**Comment by kvcops** [comment]
Well it's working well for samsung s20 ultra and iPhone 14 pro Max...

**Comment by kvcops** [comment]
![image](https://github.com/user-attachments/assets/55d0c098-e350-48b5-9d60-d277e4fadf1a)
![image](https://github.com/user-attachments/assets/776cc426-dad6-488a-905d-0e60f4bf706b)

**Comment by techy4shri** [comment]
@kvcops so we are closing this issue then?
