### ISSUE TITLE
Adding a Progress Bar to the top of the site

### ISSUE THREAD

**Issue by Dishaaa-T** [kvcops/KV-Nexus#65]
Adding a Progress Bar to the top of site to facilitate navigation through the site as it makes it easier to track progress through the web page 

![image](https://github.com/user-attachments/assets/147c8297-3c59-4e73-8cdf-2a911e518c5e)

I would like to add it in such a way

**Comment by techy4shri** [comment]
Not needed, closing this for now. @kvcops
