### ISSUE TITLE
DOCS: Add Project-Setup guide 

### ISSUE THREAD

**Issue by yashksaini-coder** [kvcops/KV-Nexus#66]
@kvcops I proposed to add a proper Project setup-guide that will be used to create & setup the firebase project on the Contributors side. This will allow new contributors to easily setup the project on their end. 

As the project uses Firebase for Database & Storage I will add the proper steps in simple words, with a proper video clips if possible. 

Optional: I would add steps with clips to get all the API keys.

**Comment by yashksaini-coder** [comment]
As discussed in above approach I will raise the PR in few days, as Diwali Break is due.

**Comment by techy4shri** [comment]
@yashksaini-coder update?

**Comment by techy4shri** [comment]
@yashksaini-coder you have 24 hours to reply, after which I will be closing this issue.

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder you have 24 hours to reply and raise a PR as this is a level 1 issue, after which I will be closing this issue.

Got it. I will raise the PR as soon as I get time after clg
