### ISSUE TITLE
ADD CICD Workflows for GITHUB Automation

### ISSUE THREAD

**Issue by AnushkaChouhan25** [kvcops/KV-Nexus#67]
Implement Continuous Integration and Continuous Deployment (CI/CD) workflows for automating tasks on GitHub. This will streamline the development process by automating testing, builds, and deployments on every code push or pull request.

- Auto Comment on Issue
- Auto Comment on PR
- Auto Comment on PR Merge
- Close Issues on PR Merge
- Comment on Issue Close 
- Auto Label PRs

**Comment by ShashwatAgrawal20** [comment]
![it-already-exists](https://github.com/user-attachments/assets/9790be2a-f120-40c9-8d03-373b6130e1f5)

**CLOSING**
