### ISSUE TITLE
Adding Dockerfile for easy usage/installation of Project in any environment

### ISSUE THREAD

**Issue by mayank-0407** [kvcops/KV-Nexus#68]
Adding a Dockerfile will allow the project to run in an isolated container, simplifying setup and ensuring consistency across environments. Using Docker will be entirely optional; contributors can continue running the project as usual without Docker. However, for those who opt in, Docker provides a one-command setup (docker build and docker run) that minimizes dependency issues by creating a consistent environment. This is especially beneficial for avoiding compatibility problems when there are version changes, such as in Node.js or Flask, which can otherwise cause inconsistencies.

Impact: Optional but useful for smoother onboarding, reduced setup issues, and improved cross-system compatibility, particularly valuable if future version mismatches arise.
Prerequisites: Docker is only required for those who wish to use it; otherwise, no changes to the current workflow are necessary.

**Comment by mayank-0407** [comment]
@kvcops Please assign it to me

**Comment by ShashwatAgrawal20** [comment]
hey @mayank-0407, don't think we need this right now. 

Sorry,

![dontneedtoaddress](https://github.com/user-attachments/assets/39a00522-5b99-4782-9ddb-6cb08676272c)

**CLOSING**
