### ISSUE TITLE
Add region selection option to weather section in navbar.

### ISSUE THREAD

**Issue by atmajaa** [kvcops/KV-Nexus#69]
Currently the navbar shows weather updates of just one location. I want to improve the functionality where users can select a location and see the weather of that region.

![image](https://github.com/user-attachments/assets/97325338-e005-400d-90ad-b721df5a3611)

**Comment by atmajaa** [comment]
@kvcops please assign this to me

**Comment by ShashwatAgrawal20** [comment]
hi @atmajaa are you still working on this? how's the progress so far?

**Comment by techy4shri** [comment]
@atmajaa reply by tonight or I will be unassigning you and closing this issue.
