### ISSUE TITLE
Navbar too broad on smaller screen

### ISSUE THREAD

**Issue by Bhum-ika** [kvcops/KV-Nexus#7]
![image](https://github.com/user-attachments/assets/eef7c65b-88d6-4efa-b0b5-f6fff6c57739)

The logo should be samller accordingly and height lesser.

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by kvcops** [comment]
ok...modify the changes accordingly and check for responsiveness

**Comment by techy4shri** [comment]
It works perfectly, the flex option is there for this reason. Closing this issue now.
