### ISSUE TITLE
Enhanced scroll back button with timeline on it for smoother functioning.

### ISSUE THREAD

**Issue by shriyadindi** [kvcops/KV-Nexus#70]
Enhanced scroll back button with timeline on it for smoother functioning.
![Screenshot 2024-10-31 115055](https://github.com/user-attachments/assets/7451962d-d51f-4a5f-a7a4-37a38c7f351e)

**Comment by kvcops** [comment]
Yep...this seems nice...but choose the color gradient that is suitable for the website

**Comment by shriyadindi** [comment]
@kvcops Okay

**Comment by kvcops** [comment]
Ok...be waiting for your pr..

**Comment by shriyadindi** [comment]
@kvcops Done.
https://github.com/kvcops/KV-Nexus/pull/72

**Comment by kvcops** [comment]
Thank you @shriyadindi  :)
