### ISSUE TITLE
Feat - Footer 

### ISSUE THREAD

**Issue by Molza01** [kvcops/KV-Nexus#73]
There should be some footer contents like quicklinks of about us, features, Contact, Team and faq and also some brief about the website.
The Footer Area will look more attractive and good.

Screenshot!!
![Screenshot 2024-11-03 182417](https://github.com/user-attachments/assets/64a61d1d-66e8-4ed2-ab3b-eb26aa1239db)

So please assign me this issue under
Name: Sandesh Shinde
Level 2
Role : gssoc-ext

**Comment by kvcops** [comment]
As of now it's not needed ...hoping more contributions from you in the future
