### ISSUE TITLE
Add contributors page

### ISSUE THREAD

**Issue by Son7c** [kvcops/KV-Nexus#76]
I would add anew page dedicated to all the contributors in this project which will display the stats of this project ex- no. of forks, stars etc. and also show stats of the contributors , no. of contributions done and also i would add cool animation on hovering contributors card.

**Comment by Son7c** [comment]
@kvcops Please assign me this issue

**Comment by kvcops** [comment]
Yep... implement this feature I would like to see it by myself...then I can assign you the level

**Comment by techy4shri** [comment]
@Son7c raise the PR by tonight.
