### ISSUE TITLE
Add a Translation Tool (all language) ✨

### ISSUE THREAD

**Issue by Subhajit-2023-44** [kvcops/KV-Nexus#77]
I want to add a Translation Tool(all language) properly.

PA please assign me this task.

**Comment by Subhajit-2023-44** [comment]
@khurshed07

**Comment by Subhajit-2023-44** [comment]
@kvcops

**Comment by kvcops** [comment]
This feature is already present ...

**Comment by Subhajit-2023-44** [comment]
> This feature is already present ...

@kvcops Where?, I didn't see

**Comment by kvcops** [comment]
> > This feature is already present ...
> 
> @kvcops Where?, I didn't see

Please open these pages (chef ,story ,health ) so that you can understand
