### ISSUE TITLE
Add/Enable PWA (Progressive Web App) 🟢🌟

### ISSUE THREAD

**Issue by Subhajit-2023-44** [kvcops/KV-Nexus#78]
I want to Add PWA (Progressive Web App)..

🌟Benefits of PWAs:

Improved Performance and Speed
Offline Availability
Enhanced User Engagement
Responsive and Adaptive Design
Low Storage Requirements... & more..

please assign me for this..

**Comment by Subhajit-2023-44** [comment]
@kvcops please assign me with Level 3 and gssoc-ext label

**Comment by kvcops** [comment]
As of now the present website works well in every device...and the pages are stored in the browser cache memory...and this mobile application completely relies on the api calling...

**Comment by kvcops** [comment]
Visit the website and the features of the website once...as you are trying to raise the issues again and again that are already present
