### ISSUE TITLE
To adding the animation effect to social media icons in the footer page

### ISSUE THREAD

**Issue by Sujal1201** [kvcops/KV-Nexus#8]
### screenshot

<img width="941" alt="image" src="https://github.com/user-attachments/assets/0aaaac5e-fe9a-447d-a90a-0a9a73823232">

**Comment by Sujal1201** [comment]
Please assign me to this issue

**Comment by Wahid7852** [comment]
What are you trying to do even

**Comment by Sujal1201** [comment]
social media icons with animation effect

**Comment by kvcops** [comment]
Ok you can try it out...
