### ISSUE TITLE
Add a User Profiles page 🌟

### ISSUE THREAD

**Issue by Subhajit-2023-44** [kvcops/KV-Nexus#83]
👤✨ I want to create a normal user profile page and a profile icon in the home page navbar that redirects to the profile page...

PA please assign me for this task...

**Comment by Subhajit-2023-44** [comment]
@kvcops

**Comment by kvcops** [comment]
What's the advantage of this feature ?

**Comment by Subhajit-2023-44** [comment]
> What's the advantage of this feature ?

@kvcops Users can personalize their experience. They can update their name, profile image (avatar), email, phone number, bio.. to make the profile more reflective of their preferences. A user will feel more connected to the platform if they can customize their profile to reflect their personality or interests..

**Comment by kvcops** [comment]
So...which database would you like to use for these to store the data?
