### ISSUE TITLE
Feature Enhancement: Docs Summarizer

### ISSUE THREAD

**Issue by yashksaini-coder** [kvcops/KV-Nexus#88]
The current doc summarizer has a problem where it has strictly limited size for pdf files. I would like to present an alternative to easily allow upload of pdf files of at least 10 MB. 

@kvcops kindly review this issue & assign it to me

**Comment by techy4shri** [comment]
@yashksaini-coder raise the PR by tonight or else I will be closing this issue.

**Comment by kvcops** [comment]
> No worries @techy4shri I am closing this issue as I probably won't get time tomorrow to contribute, I will contribute to this project later, when I get time on weekends after the GSSoC @kvcops.  

It's ok...
