### ISSUE TITLE
[Feature] Add a phishing messages/links detector

### ISSUE THREAD

**Issue by bhat-shubham** [kvcops/KV-Nexus#89]
We can add a feature as to create a web-based tool that can automatically detect phishing URLs and warn users before they click on them.
Frontend:
Create a simple HTML form with a text input field and a submit button.
Use JavaScript to capture the URL and send it to the backend.
Backend:
API: Create a REST API endpoint to receive the URL.
Model Integration: Integrate the trained model into the API.
URL Processing:
Extract features from the URL.
Feed the features to the model.
Based on the model's prediction, send an appropriate response to the frontend.
Response: Send the prediction result (phishing or legitimate) back to the frontend.

**Comment by techy4shri** [comment]
@bhat-shubham nope, not working on any cybersecurity features, this is a asimple website.

**Comment by bhat-shubham** [comment]
okay understood!
