### ISSUE TITLE
[Feature]add a AI-Powered Personal Book Recommendation System

### ISSUE THREAD

**Issue by bhat-shubham** [kvcops/KV-Nexus#91]
a simple yet elegant tool that would be giving personalized suggestions based upon various factors such as mood, interests, desired learnings etc. to users about what book would be a suitable fit for them.
not just that, can also tell "why" the book is a good fit.

**Comment by kvcops** [comment]
I really don't know how this feature is useful for this platform...can you please elaborate

**Comment by techy4shri** [comment]
Closing this on account of inactivity.
