### ISSUE TITLE
there is no 404 error handler page for website

### ISSUE THREAD

**Issue by SatyamSingh8306** [kvcops/KV-Nexus#93]
![Screenshot 2024-11-08 165636](https://github.com/user-attachments/assets/87bc2cb0-cc8c-4e07-8b39-1d13fdc6ef2d)

**Comment by SatyamSingh8306** [comment]
i want to work on this please just assign me this issue along with give me design you want for 404 error page

**Comment by techy4shri** [comment]
Not working on this right now, closing this.
